### ISSUE TITLE
Failed to use the data from file by readUserDaily

### ISSUE THREAD

**Issue by LYANG258** [DOI-USGS/EGRET#364]
I tried to use the discharge data from my file, whose first column is date and second column is discharge. 
filePath <- "  "
fileName <- " "
Daily <- readUserDaily(filePath,fileName,qUnit = 2)
However, the R reminded me like that:
Error in if (sum(hour) == 0 & sum(minute) == 0) { : 
  missing value where TRUE/FALSE needed
In fact, I've used the online data, then saved them in csv, tried to use by readUserDaily and no luck.   
May I ask how could I handle that?

**Comment by LYANG258** [comment]
It seems the format of date caused it. I changed it to M/D/Y and it works

**Comment by ldecicco-USGS** [comment]
Great! I recently updated the documentation to describe the required formatting better. I can also improve cryptic message that you are reporting, so hopefully someone else will not struggle. Thanks for reporting the issue, I'll get a better message up for both readUserDaily and readUserSample.
