### ISSUE TITLE
 left-censored data

### ISSUE THREAD

**Issue by kimiakarimi** [DOI-USGS/EGRET#366]
Are there any criteria for the % of left-censored data in a sample dataset? The minNumUncen argument handles the minimum number of censored values but I was wondering if having too many censored values may overpredict the estimates. Also, how is annual load calculated when the sample dataset contains left-censored data.

**Comment by rmhirsch49** [comment]
There is no formal criteria.  A lot depends on what you are trying to do.  If we want to get a sense of overall average concentrations or fluxes I’d be comfortable with as much as 50% censored data.  But, if there were substantial changes in the reporting level then I would be much more conservative.  When looking for trends I’d be concerned when we get to more than 25% censored and even more worried if there is a trend in the reporting limits.

As to computing the annual loads, the WRTDS model makes an estimate of load for every day (regardless of whether or not there are any data on the day).  The WRTDS model gives us an expected value for the load on each day and that is what it uses.  The process for WRTDS-Kalman when there is censoring.  I can explain that if you would like that too.

Bob Hirsch

From: kimiakarimi ***@***.***>
Date: Thursday, March 9, 2023 at 3:31 PM
To: DOI-USGS/EGRET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [DOI-USGS/EGRET] left-censored data (Issue #366)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Are there any criteria for the % of left-censored data in a sample dataset? The minNumUncen argument handles the minimum number of censored values but I was wondering if having too many censored values may overpredict the estimates. Also, how is annual load calculated when the sample dataset contains left-censored data.
