### ISSUE TITLE
How readNWISSample() handles records where concentration is stored as exactly 0.0

### ISSUE THREAD

**Issue by rmhirsch49** [DOI-USGS/EGRET#373]
In the past, as I remember it, when one ran readNWISSample() and the data set contained a concentration value that was coded as exactly 0.0, the function would go ahead and do the retrieval and also send a warning message saying that this happened and that the offending values were left out of the Sample data frame that was created.

When I ran a job today I got an error message, and it never gave me the desired Sample data frame.  I was able to see when the bad data point was and redo my retrieval and go ahead, but that seems less than ideal.  Do you think I recall correctly how it was done.  I would like to have it create the Sample data frame and tell the user that these zeros were deleted.

Try this example

library(EGRET)
staC <- "01646580"
staQ <- "01646500"
param <- "00665"
Sample <- readNWISSample(staC, param) 

Then I did it again with a start date of 1980-06-01 and it worked fine (except that I couldn't get any data from before that date)

Bob

**Comment by lnaslund** [comment]
I also ran into this issue. I tried installing from GitHub and I am still getting the same error.

**Comment by rmhirsch49** [comment]
It worked fine for me.  It found one bad data point with concentration coded as 0.0, it gave me a warning, left that one value out of the Sample data frame, but did construct the Sample data frame as desired.

My code was:

# note, this was done after install from GITHUB at 5:04 EDT, October 16
library(EGRET)
staC <- "01646580"
staQ <- "01646500"
param <- "00665"
Sample <- readNWISSample(staC, param, startDate = "1970-06-01")
summary(Sample)


It ran and gave me this warning message, which looks like the warning messages I got in the past when the zero problem came up.

2: In compressData(rawSample[, totalColumns], verbose = verbose) :
  Deleted 1 rows of data because concentration was reported as 0.0, the program is unable to interpret that result and is therefore deleting it.

So, from my perspective the problem seems to be solved.  Thanks Laura.
From: Laura DeCicco ***@***.***>
Date: Monday, October 16, 2023 at 2:14 PM
To: DOI-USGS/EGRET ***@***.***>
Cc: Hirsch, Robert M ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [DOI-USGS/EGRET] How readNWISSample() handles records where concentration is stored as exactly 0.0 (Issue #373)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Try installing from GitHub and let me know if anything still is working incorrectly:

remotes::install_github("DOI-USGS/EGRET")

**Comment by ldecicco-USGS** [comment]
@lnaslund , could you paste the code you used to see the error again? Or let me know the site ID? While you are at it, paste your session info so I can try to tell if it's a dependency problem or your particular site has something funky going on:
```r
library(EGRET)
sessionInfo()
```

**Comment by lnaslund** [comment]
Apologies for the delay. The issue appears to be resolved. Thank you.
