### ISSUE TITLE
Hide messages about removing sample data when `verbose=FALSE` in `runSurvReg()`

### ISSUE THREAD

**Issue by lindsayplatt** [DOI-USGS/EGRET#375]
I was running `modelEstimation()` with `verbose=FALSE` because I am running this for a lot of sites in a pipeline and do not want messages printed to the console. Within `modelEstimation()`, `estCrossVal()` is called. And within `estCrossVal()` there is [a for loop that calls `runSurvReg()` for each row of data](https://github.com/DOI-USGS/EGRET/blob/e1630e6f709bd1cbb60d82ebe85a9ebe3393b210/R/estCrossVal.R#L66). For one of my sites, `runSurvReg()` prints the message `Removing Sample data that does not have corresponding flow data`, which then gets printed over and over and over, even with `verbose = FALSE`. It would be nice if the `verbose` setting hid this message.

Would you consider adding `if(verbose)` to [this line](https://github.com/DOI-USGS/EGRET/blob/e1630e6f709bd1cbb60d82ebe85a9ebe3393b210/R/runSurvReg.R#L50)?

**Comment by ldecicco-USGS** [comment]
No problem, PR will be coming soon! I'm sure there are other messages hidden around that could use some if(verbose). We did at one point at least change many of the `cat` functions to `message`. If it's a message, depending on how you are running it you might be able to hide the messages.

Can't wait to hear how you're using `EGRET`!

**Comment by lindsayplatt** [comment]
It is a message, so I have a workaround with `suppressMessages()` right now. Just thought I'd mention it anyways :)

Using WRTDS for gap-filling some salinity data that will be used in a timeseries clustering analysis. The timeseries clustering algorithms do not like NAs!

**Comment by ldecicco-USGS** [comment]
Not sure why the PR didn't close this issue, but if you install via `remotes` it should be verbosed now. Sounds like a really cool application for WRTDS.
